import Foundation

/// Library of how-to instructions for exercises generated by the training plan engine.
/// Keyed by normalized exercise name. Returns a default fallback when an exercise isn't catalogued.
enum ExerciseLibrary {

    struct Instructions {
        let steps: [String]
        let formCues: [String]
        let commonMistakes: [String]
        let muscleGroups: [String]
    }

    static func instructions(for exerciseName: String) -> Instructions {
        let key = normalize(exerciseName)
        return catalog[key] ?? defaultInstructions(for: exerciseName)
    }

    /// Build a YouTube search URL for video demonstration.
    static func youtubeSearchURL(for exerciseName: String) -> URL {
        let query = "\(exerciseName) proper form"
            .addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? exerciseName
        return URL(string: "https://www.youtube.com/results?search_query=\(query)")!
    }

    private static func normalize(_ name: String) -> String {
        name.lowercased()
            .replacingOccurrences(of: "-", with: " ")
            .trimmingCharacters(in: .whitespaces)
    }

    private static func defaultInstructions(for name: String) -> Instructions {
        Instructions(
            steps: [
                "Watch a quick form video before your first set.",
                "Start with light or no weight to learn the movement pattern.",
                "Move with control. Slower on the lowering phase than the lifting phase.",
                "Breathe out on exertion, breathe in on the return."
            ],
            formCues: [
                "Keep your core engaged throughout the movement.",
                "Maintain a neutral spine (no rounding or arching unless the exercise calls for it).",
                "Stop the set if form breaks down."
            ],
            commonMistakes: [
                "Going too heavy too soon.",
                "Using momentum instead of muscle control.",
                "Holding your breath."
            ],
            muscleGroups: []
        )
    }

    // MARK: - Catalogue

    private static let catalog: [String: Instructions] = [
        "burpees": Instructions(
            steps: [
                "Start standing with feet shoulder-width apart.",
                "Drop into a squat and place your hands on the floor in front of you.",
                "Jump or step your feet back into a high plank.",
                "Optional: drop your chest to the floor for a push-up.",
                "Jump or step your feet back to your hands.",
                "Explode upward into a jump with arms overhead."
            ],
            formCues: [
                "Land softly with knees slightly bent.",
                "Keep your core tight in the plank — no sagging hips.",
                "Move at a sustainable pace; quality over speed."
            ],
            commonMistakes: [
                "Letting hips drop in the plank position.",
                "Rushing through reps and losing form.",
                "Locking out knees on landing."
            ],
            muscleGroups: ["Full Body", "Cardio"]
        ),

        "mountain climbers": Instructions(
            steps: [
                "Start in a high plank position, hands directly under shoulders.",
                "Drive one knee toward your chest.",
                "Quickly switch legs, driving the other knee in.",
                "Continue alternating at a controlled, brisk pace."
            ],
            formCues: [
                "Keep hips level — don't bounce them up and down.",
                "Maintain a straight line from head to heels.",
                "Engage your core to control hip movement."
            ],
            commonMistakes: [
                "Hips rising too high (looks like a pike).",
                "Hands drifting forward of shoulders.",
                "Going too fast and losing form."
            ],
            muscleGroups: ["Core", "Cardio"]
        ),

        "jump squats": Instructions(
            steps: [
                "Stand with feet shoulder-width apart.",
                "Lower into a squat, keeping chest up and weight in your heels.",
                "Explode upward, jumping as high as you can.",
                "Land softly, immediately lowering into the next squat."
            ],
            formCues: [
                "Land with soft knees, not locked.",
                "Keep your chest up throughout.",
                "Reset your form before each jump."
            ],
            commonMistakes: [
                "Letting knees cave inward.",
                "Landing flat-footed or stiff-legged.",
                "Rounding the back at the bottom of the squat."
            ],
            muscleGroups: ["Quads", "Glutes", "Cardio"]
        ),

        "high knees": Instructions(
            steps: [
                "Stand tall with feet hip-width apart.",
                "Run in place, driving your knees up toward your chest.",
                "Pump your arms in rhythm with your legs.",
                "Stay on the balls of your feet."
            ],
            formCues: [
                "Aim to bring each knee to hip level or higher.",
                "Keep your torso upright — don't lean back.",
                "Land softly on the balls of your feet."
            ],
            commonMistakes: [
                "Leaning back excessively.",
                "Knees not coming high enough.",
                "Heavy, flat-footed landings."
            ],
            muscleGroups: ["Cardio", "Hip Flexors"]
        ),

        "squats": Instructions(
            steps: [
                "Stand with feet shoulder-width apart, toes slightly turned out.",
                "Brace your core and look forward.",
                "Push your hips back as if sitting into a chair.",
                "Lower until your thighs are parallel to the floor (or as deep as you can with good form).",
                "Drive through your heels to return to standing."
            ],
            formCues: [
                "Knees track over your toes — don't let them cave in.",
                "Keep your chest up and back flat.",
                "Weight in your heels and mid-foot, not your toes."
            ],
            commonMistakes: [
                "Knees caving inward.",
                "Heels rising off the floor.",
                "Rounding the lower back at depth."
            ],
            muscleGroups: ["Quads", "Glutes", "Hamstrings"]
        ),

        "push ups": Instructions(
            steps: [
                "Start in a high plank with hands slightly wider than shoulders.",
                "Engage your core and glutes — body forms a straight line.",
                "Lower your chest to the floor by bending your elbows at a 45-degree angle.",
                "Press through your palms to return to the starting position."
            ],
            formCues: [
                "Keep elbows at ~45° from your torso, not flared to 90°.",
                "Maintain a straight line from head to heels.",
                "Look slightly ahead of your hands, not down."
            ],
            commonMistakes: [
                "Sagging hips or piked-up butt.",
                "Flaring elbows wide (stresses shoulders).",
                "Partial range of motion — not lowering far enough."
            ],
            muscleGroups: ["Chest", "Shoulders", "Triceps"]
        ),

        "lunges": Instructions(
            steps: [
                "Stand tall with feet hip-width apart.",
                "Step forward with one leg, lowering your hips until both knees bend at 90°.",
                "Your front knee should be over (not past) your ankle.",
                "Push through your front heel to return to standing.",
                "Alternate legs or complete all reps on one side first."
            ],
            formCues: [
                "Keep your torso upright.",
                "Step far enough forward that your front shin stays vertical.",
                "Lower straight down — don't lean forward."
            ],
            commonMistakes: [
                "Front knee tracking past the toes.",
                "Stepping too short, putting strain on the knee.",
                "Leaning the torso forward."
            ],
            muscleGroups: ["Quads", "Glutes", "Hamstrings"]
        ),

        "plank": Instructions(
            steps: [
                "Place forearms on the floor, elbows directly under shoulders.",
                "Extend your legs back, balancing on your toes.",
                "Form a straight line from head to heels.",
                "Hold for the prescribed time, breathing steadily."
            ],
            formCues: [
                "Squeeze your glutes and brace your core.",
                "Look at the floor between your hands — neutral neck.",
                "Don't let your hips sag or pike up."
            ],
            commonMistakes: [
                "Hips dropping toward the floor.",
                "Holding your breath.",
                "Looking up (compressing the neck)."
            ],
            muscleGroups: ["Core", "Shoulders"]
        ),

        "bench press": Instructions(
            steps: [
                "Lie flat on a bench, eyes under the bar.",
                "Grip the bar slightly wider than shoulder-width.",
                "Unrack the bar and hold it directly above your chest.",
                "Lower the bar with control to your mid-chest.",
                "Press the bar back up to the starting position."
            ],
            formCues: [
                "Keep your feet flat on the floor.",
                "Maintain a slight arch in your lower back, shoulder blades pinched.",
                "Wrists stacked over elbows throughout the lift."
            ],
            commonMistakes: [
                "Bouncing the bar off the chest.",
                "Flaring elbows out to 90°.",
                "Lifting feet off the floor."
            ],
            muscleGroups: ["Chest", "Shoulders", "Triceps"]
        ),

        "overhead press": Instructions(
            steps: [
                "Stand with feet shoulder-width apart, bar at shoulder height.",
                "Grip the bar slightly wider than shoulder-width.",
                "Brace your core and squeeze your glutes.",
                "Press the bar straight up overhead, locking out your arms.",
                "Lower with control back to shoulder level."
            ],
            formCues: [
                "Keep your ribcage stacked over your hips — no leaning back.",
                "Push your head through your arms at the top.",
                "Bar travels in a straight line, close to your face."
            ],
            commonMistakes: [
                "Excessive lower back arch.",
                "Pressing the bar forward instead of straight up.",
                "Letting elbows flare wide."
            ],
            muscleGroups: ["Shoulders", "Triceps", "Core"]
        ),

        "deadlifts": Instructions(
            steps: [
                "Stand with feet hip-width apart, bar over mid-foot.",
                "Hinge at your hips and grip the bar just outside your knees.",
                "Brace your core, flatten your back, and engage your lats.",
                "Drive through your heels, extending hips and knees together.",
                "Lock out at the top by squeezing your glutes.",
                "Reverse the motion to return the bar to the floor."
            ],
            formCues: [
                "Bar stays close to your body the entire lift.",
                "Push the floor away with your feet, don't yank the bar.",
                "Neutral spine — chest up, not chin up."
            ],
            commonMistakes: [
                "Rounding the lower back.",
                "Bar drifting away from the body.",
                "Hyperextending at the top."
            ],
            muscleGroups: ["Hamstrings", "Glutes", "Back", "Core"]
        ),

        "pull ups": Instructions(
            steps: [
                "Grip a pull-up bar with palms facing away, slightly wider than shoulder-width.",
                "Hang with arms fully extended, shoulders engaged.",
                "Pull your chest toward the bar, driving elbows down.",
                "Pause when your chin clears the bar.",
                "Lower with control to a full hang."
            ],
            formCues: [
                "Lead with your chest, not your chin.",
                "Squeeze your shoulder blades down and back.",
                "Engage your core to prevent swinging."
            ],
            commonMistakes: [
                "Using momentum (kipping when training strict pull-ups).",
                "Not going to a full hang at the bottom.",
                "Pulling with arms only — neglecting the lats."
            ],
            muscleGroups: ["Back", "Biceps"]
        ),

        "barbell rows": Instructions(
            steps: [
                "Stand with feet hip-width apart, bar in front of you.",
                "Hinge at the hips with a flat back, knees slightly bent.",
                "Grip the bar slightly wider than shoulder-width.",
                "Pull the bar to your lower chest or upper abs.",
                "Lower with control to a full extension."
            ],
            formCues: [
                "Keep your torso angle fixed throughout the lift.",
                "Pull with your back, not your arms.",
                "Squeeze your shoulder blades at the top."
            ],
            commonMistakes: [
                "Rounding the back.",
                "Standing up as you pull (jerking).",
                "Yanking the bar instead of controlling the motion."
            ],
            muscleGroups: ["Back", "Biceps", "Rear Delts"]
        ),

        "bicep curls": Instructions(
            steps: [
                "Stand with dumbbells at your sides, palms facing forward.",
                "Keep your elbows pinned to your sides.",
                "Curl the weights up toward your shoulders.",
                "Squeeze your biceps at the top.",
                "Lower with control to the starting position."
            ],
            formCues: [
                "Don't swing your body to lift the weight.",
                "Full range of motion — fully extend at the bottom.",
                "Control the lowering phase."
            ],
            commonMistakes: [
                "Using momentum from the hips.",
                "Letting elbows drift forward.",
                "Half-reps at heavy weights."
            ],
            muscleGroups: ["Biceps", "Forearms"]
        ),

        "tricep dips": Instructions(
            steps: [
                "Position yourself on parallel bars or a sturdy bench edge.",
                "Support your weight with your arms, body upright.",
                "Lower yourself by bending your elbows to about 90°.",
                "Press back up to the starting position."
            ],
            formCues: [
                "Keep elbows tucked behind you, not flared.",
                "Chest up, shoulders down and back.",
                "Don't dip lower than 90° at the elbow."
            ],
            commonMistakes: [
                "Shoulders rolling forward.",
                "Going too deep and stressing the shoulder.",
                "Bouncing out of the bottom."
            ],
            muscleGroups: ["Triceps", "Chest", "Shoulders"]
        ),

        "running jogging": Instructions(
            steps: [
                "Start with a 3-5 minute walking warmup.",
                "Transition to an easy jog, focusing on relaxed breathing.",
                "Land mid-foot under your hips, not heel-first ahead of your body.",
                "Maintain a slight forward lean from the ankles.",
                "Cool down with 3-5 minutes of walking."
            ],
            formCues: [
                "Shoulders relaxed, arms swinging naturally.",
                "Eyes forward, not down at your feet.",
                "Cadence of ~170-180 steps per minute is ideal."
            ],
            commonMistakes: [
                "Overstriding (heel-striking far ahead).",
                "Tense shoulders and clenched fists.",
                "Going too fast on easy runs."
            ],
            muscleGroups: ["Legs", "Cardio"]
        ),

        "stretching": Instructions(
            steps: [
                "Hold each stretch for 20-30 seconds.",
                "Breathe deeply throughout — never hold your breath.",
                "Go to the point of mild tension, never sharp pain.",
                "Focus on the muscle groups you worked today."
            ],
            formCues: [
                "Stretch warm muscles, not cold ones.",
                "Don't bounce — hold a steady position.",
                "Both sides equally if it's a one-sided stretch."
            ],
            commonMistakes: [
                "Bouncing (ballistic stretching).",
                "Holding breath during the stretch.",
                "Pushing into sharp pain."
            ],
            muscleGroups: ["Flexibility", "Recovery"]
        ),

        "foam rolling": Instructions(
            steps: [
                "Place the foam roller under the target muscle.",
                "Use slow, controlled motion — 1 inch per second.",
                "When you find a tender spot, pause for 20-30 seconds.",
                "Cover the full length of the muscle, 1-2 minutes per muscle group."
            ],
            formCues: [
                "Breathe deeply and try to relax into the pressure.",
                "Avoid rolling directly on bones or joints.",
                "More pressure isn't better — moderate is most effective."
            ],
            commonMistakes: [
                "Rolling too fast.",
                "Rolling over joints.",
                "Using too much pressure and causing bruising."
            ],
            muscleGroups: ["Recovery"]
        ),

        "yoga flow": Instructions(
            steps: [
                "Move through poses in sync with your breath.",
                "Inhale to lengthen, exhale to deepen.",
                "Hold poses for 3-5 breaths or move continuously.",
                "End in a few minutes of stillness (savasana)."
            ],
            formCues: [
                "Engage your core to protect your back.",
                "Soft knees in standing poses, not locked.",
                "Modify any pose that causes pain."
            ],
            commonMistakes: [
                "Forcing flexibility instead of building it gradually.",
                "Holding the breath in challenging poses.",
                "Comparing yourself to others — work at your own pace."
            ],
            muscleGroups: ["Flexibility", "Core", "Recovery"]
        ),
    ]
}
